// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7eWcejmqd9VZ3UHqfChRgk-53k4lVZ4',
    appId: '1:116672808398:web:ec1a3ba346652b8138979f',
    messagingSenderId: '116672808398',
    projectId: 'cleaning-service-7fc62',
    authDomain: 'cleaning-service-7fc62.firebaseapp.com',
    storageBucket: 'cleaning-service-7fc62.appspot.com',
    measurementId: 'G-1E54WJ4DSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGUVlWMh6I4k7T0b5p1G4KWEvX0Y_PRY',
    appId: '1:116672808398:android:65a6ff4e2e1264c938979f',
    messagingSenderId: '116672808398',
    projectId: 'cleaning-service-7fc62',
    storageBucket: 'cleaning-service-7fc62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ONOk7wEuChfGSTkbPDLxV4CoAOsHUgk',
    appId: '1:116672808398:ios:274592ef8983481338979f',
    messagingSenderId: '116672808398',
    projectId: 'cleaning-service-7fc62',
    storageBucket: 'cleaning-service-7fc62.appspot.com',
    iosClientId: '116672808398-eq2glsqjj5vcspinesm7ng8p2ji0osn3.apps.googleusercontent.com',
    iosBundleId: 'com.cleaning-service.app',
  );
}
